<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="api_tests.xsl" type="text/xsl" ?>
<unittest-results date_time = "2012-12-30 21:23:26" tests="17" failedtests="11" failures="12" time="0.002">
<test suite="Base" name="AllocateRR" time="0"/>
<test suite="Base" name="LOGGING" time="0"><failure message="base.cpp(38) : Unhandled exception: Crash!"/></test>
<test suite="Base" name="VERSIONS" time="0"/>
<test suite="Base" name="MODEL_FILES" time="0"/>
<test suite="Base" name="LOAD_SBML" time="0"><failure message="base.cpp(69) : Unhandled exception: Crash!"/></test>
<test suite="Base" name="LISTS" time="0"/>
<test suite="SteadyState" name="DATA_FILES" time="0.001"/>
<test suite="SteadyState" name="AllocateRR" time="0"/>
<test suite="SteadyState" name="LOAD_MODEL" time="0"><failure message="steady_state.cpp(63) : Unhandled exception: Crash!"/></test>
<test suite="SteadyState" name="COMPUTE_STEADY_STATE" time="0"><failure message="steady_state.cpp(77) : steadyState(val)"/><failure message="steady_state.cpp(78) : Expected 0 +/- 1e-06 but was 4.62105e+54"/></test>
<test suite="SteadyState" name="GET_EIGENVALUE_IDS" time="0"><failure message="steady_state.cpp(81) : Unhandled exception: Crash!"/></test>
<test suite="SteadyState" name="STEADY_STATE_CONCENTRATIONS" time="0"><failure message="steady_state.cpp(137) : Unhandled exception: Crash!"/></test>
<test suite="SteadyState" name="GET_EIGENVALUES_THROW_EXCEPTION" time="0"><failure message="steady_state.cpp(167) : Unhandled exception: Crash!"/></test>
<test suite="SteadyState" name="GET_EIGENVALUES_1" time="0"><failure message="steady_state.cpp(203) : Unhandled exception: Crash!"/></test>
<test suite="SteadyState" name="GET_EIGENVALUES_2" time="0"><failure message="steady_state.cpp(254) : Unhandled exception: Crash!"/></test>
<test suite="SteadyState" name="COMPUTE_STEADY_STATE_VALUES" time="0"><failure message="steady_state.cpp(300) : Unhandled exception: Crash!"/></test>
<test suite="SteadyState" name="FULL_JACOBIAN" time="0"><failure message="steady_state.cpp(309) : Unhandled exception: Crash!"/></test>
</unittest-results>
